# Generated by Django 5.0.6 on 2025-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_educationdetail_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Backup UPI ID'),
        ),
    ]
