# Generated by Django 5.0.6 on 2025-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_subscription_custom_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_indian_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
