# Generated by Django 5.0.6 on 2025-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_titel_description_service_page_page_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_page',
            name='left_height',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='service_page',
            name='left_width',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='service_page',
            name='right_height',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='service_page',
            name='right_width',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
