# Generated by Django 5.0.6 on 2025-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_alter_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
