# Generated by Django 5.0.6 on 2025-06-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0010_answer_is_second_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_second_attempt',
        ),
        migrations.AddField(
            model_name='question',
            name='is_second_attempt',
            field=models.BooleanField(default=False, help_text='Mark this for second attempt question set.'),
        ),
    ]
