# Generated by Django 5.0.6 on 2025-08-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0011_remove_answer_is_second_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='examination.question'),
        ),
    ]
