# Generated by Django 5.0.6 on 2025-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0004_teammember_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='mission_description',
            field=models.TextField(default='Empower the next generation of talent by connecting exceptional candidates with forward-thinking companies that value fresh perspectives and innovative solutions.'),
        ),
        migrations.AddField(
            model_name='feature',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=200),
        ),
    ]
