# Generated by Django 5.0.6 on 2025-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0006_remove_feature_mission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscontent',
            name='mission_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
