# Generated by Django 5.0.6 on 2025-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0007_alter_aboutuscontent_mission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscontent',
            name='mission_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
