# Generated by Django 5.0.6 on 2025-06-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_rename_image_supportinfo_support_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportinfo',
            name='map_description',
            field=models.TextField(blank=True, help_text='Short description under the map title', null=True),
        ),
        migrations.AddField(
            model_name='supportinfo',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Paste your Google Maps iframe embed URL', null=True),
        ),
        migrations.AddField(
            model_name='supportinfo',
            name='map_title',
            field=models.CharField(blank=True, help_text='Title above the map (e.g., Find Us on Google Maps)', max_length=255, null=True),
        ),
    ]
