# Generated by Django 5.0.6 on 2025-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPost', '0005_remove_blogpost_blog_image_alter_blogpost_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepreference',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepreference',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepreference',
            name='revisions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
