# Generated by Django 5.0.6 on 2025-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPost', '0007_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
