# Generated by Django 5.0.6 on 2025-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPost', '0008_blogpost_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
