# Generated by Django 5.0.6 on 2025-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_customization', '0004_footer_footerportfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='feature1_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature1_icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature1_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature2_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature2_icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature3_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature3_icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='feature3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
