# Generated by Django 5.0.6 on 2025-07-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_customization', '0005_herosection_feature1_desc_herosection_feature1_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('point1_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('point1_title', models.CharField(blank=True, max_length=100, null=True)),
                ('point1_desc', models.TextField(blank=True, null=True)),
                ('point2_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('point2_title', models.CharField(blank=True, max_length=100, null=True)),
                ('point2_desc', models.TextField(blank=True, null=True)),
                ('point3_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('point3_title', models.CharField(blank=True, max_length=100, null=True)),
                ('point3_desc', models.TextField(blank=True, null=True)),
                ('point4_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('point4_title', models.CharField(blank=True, max_length=100, null=True)),
                ('point4_desc', models.TextField(blank=True, null=True)),
                ('point5_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('point5_title', models.CharField(blank=True, max_length=100, null=True)),
                ('point5_desc', models.TextField(blank=True, null=True)),
                ('point6_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('point6_title', models.CharField(blank=True, max_length=100, null=True)),
                ('point6_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
