# Generated by Django 5.0.6 on 2025-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0016_projectdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='candidate_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
