# Generated by Django 5.0.6 on 2025-07-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0018_progressstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressstage',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='stage_proofs/'),
        ),
    ]
